@startuml
package "core" {
  [Item.java]
  [Model.java]

}

package "ui" {
  [App.java]
  [SplashScreen.java]
  folder "Controllers"
  folder "Controls"
  folder "Effects" 
}

component [Javafx] {
   component "fxml"
}

database "database" {
  folder "dao" {
  }
  folder "daoImpl" {
  }
  [ConnectionHandler.java]
}

Javafx <-> ui
ui <-> fxml
ConnectionHandler.java <..> ui
ConnectionHandler.java <..> daoImpl
ConnectionHandler.java ..> core
ui <..> database
Item.java <..> ConnectionHandler.java
SplashScreen.java ..> App.java

dao <-> daoImpl
Model.java -> Item.java
@enduml