tasks:
  - init: sdk use java 14.0.2.j9-adpt
    command: cd foundly
  - command: cd foundly
image:
  file: .gitpod.Dockerfile

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
  # used by rest-api and web-client
  - port: 8098
  # used by web-client devServer
  - port: 8080

