@startuml
package Model <<Folder>> {
    class Item {
    long id
    String title
    String description
    State state
    String email
    String phone
    String image
    LocalDateTime date

    }
}

package json <<Folder>> {

    class ItemSerializer {
        Item serialize()
    }

    class ItemDeserializer {
        Item deserialize()
    }
}

package uiDataaccess <<Cloud>> {

}

uiDataaccess -left-> Item : uses
note right of uiDataaccess: See separate diagram for ui-module
Model -down-> json : uses
@enduml