@startuml
/' Prøver å få det til å se litt pent ut med together'/
together {
  package "UI" {
    folder "container" 
    folder "controller"
    folder "control"
    folder "effect" 
    [App.java]
    [SplashScreen.java]
   }
  package "web-client" { 
    folder "components"
    folder "services"
    [App.vue]
   }
}
package "core" {
  folder "json"
  folder "model"
}
together {
    package "rest-api" {
    folder "exception" 
    folder "persistence"
    folder "presentation"
    folder "service" 
    [RestApi.java]
    [WebConfig.java]
   }
   database "database" {
   [H2-database]
   }
}
[persistence] <..> [H2-database]
[service] <..> [components]
[service] <..> UI
core <..> container
@enduml